### ISSUE TITLE
[ECE-Tools] Multi-threaded SCD Doesn’t Work as Expected

### ISSUE THREAD

**Issue by YPyltiai** [magento/ece-tools#503]
Internal ID: `MAGECLOUD-3611`

**Background:**
* https://magentocommeng.slack.com/archives/C8CBB6K9V/p1557737159442700
* #457 added multi-thread SCD back since it was removed in earlier versions during refactoring
* Users now observe issues with SCD, which are common across multiple projects

**To Do:**
* Investigate if it’s the issue in code or some library is outdated (per @hostep comment)
* Check if thread override for compact strategy still works as expected (in Slack users mentioned that it looks broken too)
* Review PR mentioned in Slack, which is possibly able to help resolving the issue

**Comment by hostep** [comment]
Since the free Slack version doesn't keep messages around for a long time, here's some links which might stand the test of time a bit better :)
- first bullet point refers to some observations I made on my local machine (this doesn't mean per sé that it will happen on the cloud): https://github.com/magento/magento2/pull/22607#issuecomment-489725835 & https://github.com/magento/magento2/pull/22607#issuecomment-491031541
- the third bullet point refers to the same PR: https://github.com/magento/magento2/pull/22607

Additionally, @ihor-sviziev is on a mission to find more issues with (multi-threaded) SCD execution which might be interesting to follow, for example:
- https://github.com/magento/magento2/issues/22880
- https://github.com/magento/magento2/issues/22882
- https://github.com/magento/magento2/issues/22883

**Comment by ihor-sviziev** [comment]
I think better idea to fix these issues not inside ece tools, but inside magento itself and maybe apply these patches inside ece tools for versions that don’t have these fixes

For two issues I already created PRs: 
https://github.com/magento/magento2/pull/22884
https://github.com/magento/magento2/pull/22886

**Comment by oshmyheliuk** [comment]
@ihor-sviziev Thank you. 
We'll add patches to ece-tools after merging your fixes into the core.

**Comment by ihor-sviziev** [comment]
BTW following PR also looks related https://github.com/magento/magento2/pull/22607

**Comment by shiftedreality** [comment]
Here is a good example of failing on Travis CI builds https://travis-ci.com/magento/ece-tools/jobs/199529919

**Comment by YPyltiai** [comment]
@hostep , is https://github.com/magento/magento2/issues/22563 also related?

**Comment by ihor-sviziev** [comment]
> @hostep , is [magento/magento2#22563](https://github.com/magento/magento2/issues/22563) also related?

Yes, but it’s getting fixed by https://github.com/magento/magento2/pull/22607

**Comment by hostep** [comment]
> is magento/magento2#22563 also related?

Indeed, but it's only broken on the 2.3-develop branch, the change didn't happen yet in a stable version.

So if we're lucky, it won't be broken in 2.3.2. As long as https://github.com/magento/magento2/commit/7421dfb0a263e1f0b92af77e21051c7ffa44cbba isn't being included before https://github.com/magento/magento2/pull/22607 gets included as well. So maybe someone should talk to the people involved with releasing new versions to make sure this doesn't happen :)

**Comment by YPyltiai** [comment]
Should be fixed by #527

**Comment by YPyltiai** [comment]
Resolved in #530 
Current tests are all passing as expected
